name: Code Quality

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  Composer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          tags: composer-replacements
          load: true
          pull: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: docker run --rm --volume $PWD:/app --user $(id -u):$(id -g) composer-replacements composer install
